@startuml
title Weather App Activity Diagram - Default City and Search

start

:User opens the webapp;
:Fetch weather data from API for default city;
:Display weather data for default city;

if (Weather data for default city does not exist in DB?) then (yes)
    :Save weather data for default city to DB;
else (no)
    :Display weather data;
endif

:Fetch past 7 days' data for default city from DB;
:Display past 7 days' data for default city;

:User searches for weather by city;
:Fetch weather data from API for the searched city;
:Display weather data for the searched city;

stop

@enduml
